create extension if not exists pgcrypto;

-- Application data --------------------------------------------------------

create table category (
  id         text primary key,        -- slug, matches existing frontend ids
  name       text not null,
  icon       text not null,
  sort_order integer not null default 0
);

-- Lookup tables in place of native Postgres ENUM types.
create table order_status (
  id         text primary key,   -- 'confirmed' | 'kitchen' | 'ready'
  label      text not null,      -- admin/introspection only; frontend keeps its own label map
  sort_order integer not null default 0
);

create table order_type (
  id    text primary key,        -- 'dine-in' | 'takeout'
  label text not null
);

create table menu (
  id          integer generated by default as identity primary key, -- seeded 1..15
  category_id text not null references category(id) on delete restrict,
  name        text not null,
  description text,
  unit_price  numeric(10,2) not null check (unit_price >= 0),
  emoji       text,
  popular     boolean not null default false,
  created_at  timestamptz not null default now()
);
create index menu_category_id_idx on menu(category_id);

create table customer (
  id     uuid primary key default gen_random_uuid(),
  name   text not null,
  email  text,
  mobile text
);

create table orders (
  id            text primary key,     -- 'ORD-<epoch-ms>', generated inside create_order()
  customer_id   uuid references customer(id) on delete set null,
  customer_name text not null,        -- denormalized snapshot
  phone         text,
  order_type    text not null references order_type(id),
  table_number  text,
  notes         text,
  subtotal      numeric(10,2) not null check (subtotal >= 0),
  tax           numeric(10,2) not null check (tax >= 0),
  total         numeric(10,2) not null check (total >= 0),
  status        text not null references order_status(id) default 'confirmed',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint dine_in_requires_table check (order_type <> 'dine-in' or table_number is not null)
);
create index orders_status_idx on orders(status);

create table order_item (
  id         bigint generated by default as identity primary key,
  order_id   text not null references orders(id) on delete cascade,
  menu_id    integer not null references menu(id) on delete restrict,
  name       text not null,      -- snapshot
  emoji      text,               -- snapshot
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity   integer not null default 1 check (quantity > 0)
);
create index order_item_order_id_idx on order_item(order_id);

-- RBAC scaffolding (schema.md) — structural only, nothing reads/writes these yet

create table role (
  id        serial primary key,
  role_name text not null unique
);

create table app_user (
  id       uuid primary key default gen_random_uuid(),
  username text not null unique,
  password text not null
);

create table user_role (
  user_id uuid not null references app_user(id) on delete cascade,
  role_id integer not null references role(id) on delete cascade,
  primary key (user_id, role_id)
);

create table permission (
  id              serial primary key,
  permission_name text not null unique
);

create table role_permission (
  role_id       integer not null references role(id) on delete cascade,
  permission_id integer not null references permission(id) on delete cascade,
  primary key (role_id, permission_id)
);

-- Row Level Security --------------------------------------------------------

alter table category        enable row level security;
alter table order_status    enable row level security;
alter table order_type      enable row level security;
alter table menu            enable row level security;
alter table customer        enable row level security;
alter table orders          enable row level security;
alter table order_item      enable row level security;
alter table role            enable row level security;
alter table app_user        enable row level security;
alter table user_role       enable row level security;
alter table permission      enable row level security;
alter table role_permission enable row level security;

create policy "category public read" on category for select to anon, authenticated using (true);
create policy "order_status public read" on order_status for select to anon, authenticated using (true);
create policy "order_type public read" on order_type for select to anon, authenticated using (true);
create policy "menu public read" on menu for select to anon, authenticated using (true);

create policy "customer public insert" on customer for insert to anon, authenticated with check (true);
-- no select policy on customer: write-only PII vault, never listed back to clients

create policy "orders public read" on orders for select to anon, authenticated using (true);
create policy "orders public insert" on orders for insert to anon, authenticated with check (status = 'confirmed');
create policy "orders public update" on orders for update to anon, authenticated using (true) with check (true);

create policy "order_item public read" on order_item for select to anon, authenticated using (true);
create policy "order_item public insert" on order_item for insert to anon, authenticated with check (true);

-- RBAC tables: RLS enabled, zero policies = deliberate deny-all for anon/authenticated.

-- Status transition enforcement ---------------------------------------------
-- order_status/order_type are lookup tables, not native enums, so the FK
-- only guarantees the value exists — this trigger is what actually
-- constrains the legal transition sequence.

create or replace function enforce_order_status_transition()
returns trigger language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'confirmed' and new.status = 'kitchen') or
      (old.status = 'kitchen'   and new.status = 'ready')
    ) then
      raise exception 'Invalid order status transition: % -> %', old.status, new.status;
    end if;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger orders_enforce_status_transition
  before update on orders
  for each row execute function enforce_order_status_transition();

-- Atomic order creation -------------------------------------------------------

create or replace function create_order(
  p_customer_name text, p_phone text, p_order_type text,
  p_table_number text, p_notes text, p_items jsonb,
  p_subtotal numeric, p_tax numeric, p_total numeric
)
returns orders language plpgsql security invoker as $$
declare
  v_customer_id uuid;
  v_order_id    text := 'ORD-' || (floor(extract(epoch from clock_timestamp()) * 1000))::bigint;
  v_item        jsonb;
  v_order       orders;
begin
  insert into customer (name, mobile) values (p_customer_name, p_phone) returning id into v_customer_id;

  insert into orders (id, customer_id, customer_name, phone, order_type, table_number, notes, subtotal, tax, total)
  values (v_order_id, v_customer_id, p_customer_name, p_phone, p_order_type, p_table_number, p_notes, p_subtotal, p_tax, p_total)
  returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items) loop
    insert into order_item (order_id, menu_id, name, emoji, unit_price, quantity)
    values (v_order_id, (v_item->>'menu_id')::int, v_item->>'name', v_item->>'emoji',
            (v_item->>'price')::numeric, (v_item->>'quantity')::int);
  end loop;

  return v_order;
end;
$$;

grant execute on function create_order(text, text, text, text, text, jsonb, numeric, numeric, numeric)
  to anon, authenticated;
